version: '3.8'

services:
  test_web_app:
    container_name: test_web_app
    build:
      context: .
      dockerfile: Dockerfile
    command: "pytest -vv"
    volumes:
      - .:/app
    networks:
      - web_app_network
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    ports:
      - "8080:8080"

networks:
  web_app_network:
    external: true
